spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beaver_community?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    database: 1
    port: 6379
    password: 123456
    timeout: 3000ms

logging:
  level:
    root: info
    com.macro.mall: info

#系统配置
system:
  sysDomain: http://127.0.0.1:8088
  frontDomain: http://localhost:8090
  defaultRole: 9
  web3:
    chainId: 534351
    rpcHost: https://sepolia-rpc.scroll.io
    privateKey: keys/private_key
    domain: ""
    contracts: "0x9a835ed238356cf3be47910bf19c3953d1bb81cf"
    domainVersion: ""
    listenerSwitch: false



